<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<PropertyGroup>
		<Version>2.2.0</Version>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.0" />
	  <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.5" />
	</ItemGroup>

	<ItemGroup>
	<Content Include="..\db\sql_server_config.json" Link="db\sql_server_config.json">
		<CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</Content>
	<Content Include="..\db\db_settings.json" Link="db\db_settings.json">
		<CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</Content>
	</ItemGroup>	

</Project>
